/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Algorithms88"
 * 	found in "asn1/rfc3279-PKIX1Algorithms88.asn1"
 * 	`asn1c -S asn1c/skeletons -pdu=all -pdu=Certificate -fwide-types -fcompound-names -no-gen-OER -no-gen-PER -no-gen-example`
 */

#include "EcpkParameters.h"

static asn_TYPE_member_t asn_MBR_EcpkParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EcpkParameters, choice.ecParameters),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ECParameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecParameters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EcpkParameters, choice.namedCurve),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"namedCurve"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EcpkParameters, choice.implicitlyCA),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"implicitlyCA"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_EcpkParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 2, 0, 0 }, /* implicitlyCA */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 1, 0, 0 }, /* namedCurve */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* ecParameters */
};
static asn_CHOICE_specifics_t asn_SPC_EcpkParameters_specs_1 = {
	sizeof(struct EcpkParameters),
	offsetof(struct EcpkParameters, _asn_ctx),
	offsetof(struct EcpkParameters, present),
	sizeof(((struct EcpkParameters *)0)->present),
	asn_MAP_EcpkParameters_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EcpkParameters = {
	"EcpkParameters",
	"EcpkParameters",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_EcpkParameters_1,
	3,	/* Elements count */
	&asn_SPC_EcpkParameters_specs_1	/* Additional specs */
};

